[book]
authors = ["cuihairu"]
language = "zh"
multilingual = false
src = "docs"
title = "Hello CPP"

[preprocessor.katex]
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["js/mermaid.min.js", "js/mermaid-init.js"]
